name: belajar_dart_library
description: A starting point for Dart libraries or applications.
version: 1.5.0
homepage: https://github.com/username/belajar_dart_library
repository: https://github.com/username/belajar_dart_library
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
